# (c) 1992-2020 Intel Corporation.                            
# Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
# and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
# and/or other countries. Other marks and brands may be claimed as the property  
# of others. See Trademarks on intel.com for full list of Intel trademarks or    
# the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
# Your use of Intel Corporation's design tools, logic functions and other        
# software and tools, and its AMPP partner logic functions, and any output       
# files any of the foregoing (including device programming or simulation         
# files), and any associated documentation or information are expressly subject  
# to the terms and conditions of the Altera Program License Subscription         
# Agreement, Intel MegaCore Function License Agreement, or other applicable      
# license agreement, including, without limitation, that your use is for the     
# sole purpose of programming logic devices manufactured by Intel and sold by    
# Intel or its authorized distributors.  Please refer to the applicable          
# agreement for further details.                                                 


# TCL File Generated by Component Editor 15.0
# Mon Jul 27 17:15:23 EDT 2015
# DO NOT MODIFY


# 
# acl_rom_module "Sys Description ROM" v1.0
#  2015.07.27.17:15:23
# OpenCL Sys Description ROM
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module acl_rom_module
# 
set_module_property DESCRIPTION "OpenCL Sys Description ROM"
set_module_property NAME acl_rom_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP OpenCL
set_module_property AUTHOR "Kris Kang"
set_module_property DISPLAY_NAME "Sys Description ROM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL acl_rom_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file acl_rom_module.v SYSTEM_VERILOG PATH acl_rom_module.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL acl_rom_module
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file acl_rom_module.v SYSTEM_VERILOG PATH acl_rom_module.v TOP_LEVEL_FILE

# 
# parameters
# 
add_parameter ASYNC_RESET INTEGER 1
set_parameter_property ASYNC_RESET DEFAULT_VALUE 1
set_parameter_property ASYNC_RESET DISPLAY_NAME ASYNC_RESET
set_parameter_property ASYNC_RESET TYPE INTEGER
set_parameter_property ASYNC_RESET UNITS None
set_parameter_property ASYNC_RESET HDL_PARAMETER true
add_parameter SYNCHRONIZE_RESET INTEGER 1
set_parameter_property SYNCHRONIZE_RESET DEFAULT_VALUE 0
set_parameter_property SYNCHRONIZE_RESET DISPLAY_NAME SYNCHRONIZE_RESET
set_parameter_property SYNCHRONIZE_RESET TYPE INTEGER
set_parameter_property SYNCHRONIZE_RESET UNITS None
set_parameter_property SYNCHRONIZE_RESET HDL_PARAMETER true
add_parameter INIT_FILE STRING sys_description.hex
set_parameter_property INIT_FILE DEFAULT_VALUE sys_description.hex
set_parameter_property INIT_FILE DISPLAY_NAME INIT_FILE
set_parameter_property INIT_FILE TYPE STRING
set_parameter_property INIT_FILE UNITS None
set_parameter_property INIT_FILE HDL_PARAMETER true
add_parameter ADDRESS_WIDTH INTEGER 4 ""
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 4
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH DESCRIPTION ""
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 64 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter FAMILY STRING "Arria 10"
set_parameter_property FAMILY DEFAULT_VALUE "Arria 10"
set_parameter_property FAMILY DISPLAY_NAME FAMILY
set_parameter_property FAMILY TYPE STRING
set_parameter_property FAMILY UNITS None
set_parameter_property FAMILY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk0
# 
add_interface clk0 clock end
set_interface_property clk0 clockRate 0
set_interface_property clk0 ENABLED true
set_interface_property clk0 EXPORT_OF ""
set_interface_property clk0 PORT_NAME_MAP ""
set_interface_property clk0 CMSIS_SVD_VARIABLES ""
set_interface_property clk0 SVD_ADDRESS_GROUP ""

add_interface_port clk0 clk clk Input 1


# 
# connection point reset0
# 
add_interface reset0 reset end
set_interface_property reset0 associatedClock clk0
set_interface_property reset0 synchronousEdges DEASSERT
set_interface_property reset0 ENABLED true
set_interface_property reset0 EXPORT_OF ""
set_interface_property reset0 PORT_NAME_MAP ""
set_interface_property reset0 CMSIS_SVD_VARIABLES ""
set_interface_property reset0 SVD_ADDRESS_GROUP ""

add_interface_port reset0 rst_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clk0
set_interface_property s0 associatedReset reset0
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 isMemoryDevice true
set_interface_property s0 isNonVolatileStorage true
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 1
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 address address Input ADDRESS_WIDTH
add_interface_port s0 readdata readdata Output DATA_WIDTH
add_interface_port s0 read read Input 1
add_interface_port s0 readdatavalid readdatavalid Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 1
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0

